# Generated by Django 2.2.1 on 2019-05-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('lote_numero', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_placa',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id_placa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Placa')),
                ('numero_serie', models.IntegerField(unique=True, verbose_name='Número de Série')),
                ('processo', models.CharField(max_length=20)),
                ('revisao_lm', models.IntegerField(verbose_name='Revisão LM')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.Lote')),
                ('id_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.Modelo_placa')),
            ],
            options={
                'db_table': 'PLACAS',
            },
        ),
    ]
