# Generated by Django 2.2.1 on 2019-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Item')),
            ],
        ),
    ]
